### PR TITLE
Schema refactor

### PR DESCRIPTION
**Pull request by jcustenborder**

### CODE REVIEW

**Comment by jcustenborder** [comment]
@patelliandrea, @gregroberti Do you mind giving this pull request a shot. This pull now has offset support. The only caveat is going forward I'm going to start requiring you to specify the `key.schema` and the `value.schema`

**Comment by jcustenborder** [comment]
@mikisseth Thanks for the feedback. It didn't seem like there was a lot of use with that feature. I have been thinking about adding a helper class that would give you this functionality. For example you'd run `java <some class> <path to csv>` and it would generate a schema for you to place in the config. Would functionality like this work for you? The usages I have seen were using this to import data with strong types like integer, long, etc.

**Comment by mikisseth** [comment]
My use case is that I would like use the spooldir connector in a [Landoop connector UI setup](http://kafka-connect-ui.landoop.com/#/cluster/SIT), where the user may create and configure connectors through a web interface without creating or running any code. Here it is much easier for the users to add connectors if the connectors can create schemas automatically.

**Comment by jcustenborder** [comment]
So are you fine with the fact that all of the schemas were just optional
strings? I didn't see much value to that. Are you doing another step to
convert them to the correct types? IE change a string to an integer,
timestamp, etc?

**Comment by mikisseth** [comment]
Thanks for the quick answer :-)

All fields as optional strings are a great start for me. At some point it probably would be nice with automatic strong type detection, but here and now it is not critical for me to have this in the connector itself. 

If this becomes an issue for me, I could help add this functionality to the code base.

**Comment by jcustenborder** [comment]
@mikisseth, @gbehrmann, @patelliandrea, @gregroberti Can you take a look at this one? I added a command line where you can point it at a file and it will generate the config properties. For example you can use this:

```
mvn clean package
export CLASSPATH="$(find target/kafka-connect-target/usr/share/java -type f -name '*.jar' | tr '\n' ':')"
kafka-run-class com.github.jcustenborder.kafka.connect.spooldir.SchemaGenerator -type csv -f src/test/resources/com/github/jcustenborder/kafka/connect/spooldir/csv/FieldsMatch.data -c config/CSVExample.properties -i id
```

This outputs. Right now I'm outputting all optional strings for the schema. 

```properties
#Configuration was dynamically generated. Please verify before submitting.
#Mon May 15 16:42:01 CDT 2017
name=CsvSpoolDir
key.schema={"name"\:"com.github.jcustenborder.kafka.connect.model.Key","type"\:"STRUCT","isOptional"\:false,"fieldSchemas"\:{"id"\:{"type"\:"STRING","isOptional"\:true}}}
connector.class=com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector
value.schema={"name"\:"com.github.jcustenborder.kafka.connect.model.Value","type"\:"STRUCT","isOptional"\:false,"fieldSchemas"\:{"id"\:{"type"\:"STRING","isOptional"\:true},"first_name"\:{"type"\:"STRING","isOptional"\:true},"last_name"\:{"type"\:"STRING","isOptional"\:true},"email"\:{"type"\:"STRING","isOptional"\:true},"gender"\:{"type"\:"STRING","isOptional"\:true},"ip_address"\:{"type"\:"STRING","isOptional"\:true},"last_login"\:{"type"\:"STRING","isOptional"\:true},"account_balance"\:{"type"\:"STRING","isOptional"\:true},"country"\:{"type"\:"STRING","isOptional"\:true},"favorite_color"\:{"type"\:"STRING","isOptional"\:true}}}
topic=testing
input.file.pattern=^.*.csv$
csv.first.row.as.header=true
halt.on.error=false
tasks.max=1
finished.path=/tmp/spooldir/finished
```


Keep in mind once you install the connector in the classpath all you would need to do is the kafka-run-class command. What I'm really striving for in this connector is to get strongly typed data into Kafka. This will be much more optimized if you're using something like [Schema Registry](https://github.com/confluentinc/schema-registry) where you are storing the data in Avro.

**Comment by mikisseth** [comment]
Looks good :-).

The comments from https://github.com/jcustenborder/kafka-connect-spooldir/issues/18#issuecomment-291106435 are still relevant though. Compile and test are broken, Jenkins seems to agree, I haven't got access to the details for the breaking build so can't check :-(.

As mentioned in issue 18, been able to configure the Connector to automatically run the SchemaGenerator + register the (weakly typed) generated schema in the Schema Registry as a first schema version would make it easy to get started on a new format of json/csv files (no commandline necessary if using Landoop Connect UI f.ex). The initial Schema could afterwards be updated with strong types (using Landoop Schema Registry UI f.ex).

**Comment by jcustenborder** [comment]
@mikisseth The tests should be resolved now. The timezone was not being set for the date parsing. It was parsing all dates as the current timezone. Since I live in CST it worked in CST. I was in SFO and it started erroring. I corrected that issue. I'm ready to merge this.

**Comment by mikisseth** [comment]
Sweet, tests are green here in Dubai :-)

**Pull request merged**
