### PR TITLE
new header: file.parent.dir.name

### PR DESCRIPTION
**Pull request by bitsofinfo**
adds new header `file.parent.dir.name`

### CODE REVIEW

**Comment by bitsofinfo** [comment]
@jcustenborder what failed on this can't see jenkins

**Comment by jcustenborder** [comment]
It failed a checkstyle rule. Try running `mvn clean package` this will run through everything.  

```
/home/jenkins/workspace/er_kafka-connect-spooldir_PR-181/src/main/java/com/github/jcustenborder/kafka/connect/spooldir/Metadata.java:33:45: error: '=' is not preceded with whitespace.
```

**Comment by jcustenborder** [comment]
Looks like some of the unit tests are failing now.

```
[ERROR] Tests run: 11, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 2.986 s <<< FAILURE! - in com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest
[ERROR] poll[1]  Time elapsed: 0.493 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[2]  Time elapsed: 0.33 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[3]  Time elapsed: 0.301 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[4]  Time elapsed: 0.202 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[5]  Time elapsed: 0.324 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[6]  Time elapsed: 0.323 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[7]  Time elapsed: 0.354 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[ERROR] poll[8]  Time elapsed: 0.315 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
	at com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceTaskTest.lambda$null$0(SpoolDirCsvSourceTaskTest.java:76)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SpoolDirAvroSourceTaskTest.lambda$null$1:79->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirBinaryFileSourceTaskTest.lambda$null$0:38->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirCsvSourceTaskTest.lambda$null$0:76->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirJsonSourceTaskTest.lambda$null$0:56->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirJsonSourceTaskTest.lambda$null$0:56->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirJsonSourceTaskTest.lambda$null$0:56->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirJsonSourceTaskTest.lambda$null$0:56->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirJsonSourceTaskTest.lambda$null$0:56->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirSchemaLessJsonSourceTaskTest.lambda$null$0:41->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[ERROR]   SpoolDirELFSourceTaskTest.lambda$null$0:58->AbstractSpoolDirSourceTaskTest.poll:169 index:0: headers() does not match.: size() should match. ==> expected: <2> but was: <3>
[INFO] 
[ERROR] Tests run: 142, Failures: 17, Errors: 0, Skipped: 1
```

**Comment by jcustenborder** [comment]
@bitsofinfo This has been released in 2.0.62. It's already on the Confluent's Connect Hub. It'll be in the listing when the site updates.

**Comment by bitsofinfo** [comment]
awesome! thanks a ton for quick turnaound @jcustenborder !

**Comment by jcustenborder** [comment]
No problem. Most of this is automated through Jenkins. I just need to figure out a good way to proxy the build logs in the case of a build error.

**Pull request merged**
